import java.util.*;
class ChatFun
{
public static void wait(int seconds)
{
try
{
Thread.sleep(seconds);    
}
catch(InterruptedException e)
{
e.printStackTrace();
}
}
public static void main(String args[])
{
Scanner sc=new Scanner(System.in);
String name,a;
wait(400);
System.out.print("H");
wait(400); 
System.out.print("e");
wait(400);
System.out.print("l");;
wait(400);
System.out.print("l");
wait(400);
System.out.print("o");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("f");
wait(400);
System.out.print("r");
wait(400);
System.out.print("e");
wait(400);
System.out.print("i");
wait(400);
System.out.print("n");
wait(400);
System.out.print("d");
wait(400);
System.out.print(",");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("w");
wait(400);
System.out.print("h");
wait(400);
System.out.print("a");
wait(400);
System.out.print("t");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("i");
wait(400);
System.out.print("s");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("y");
wait(400);
System.out.print("o");
wait(400);
System.out.print("u");
wait(400);
System.out.print("r");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("n");
wait(400);
System.out.print("a");
wait(400);
System.out.print("m");
wait(400);
System.out.print("e");
wait(400);
System.out.print("?");
name=sc.nextLine();
wait(400);
System.out.print("O");
wait(400);
System.out.print("o");
wait(400);
System.out.print("o");
wait(400);
System.out.print(",");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("n");
wait(400);
System.out.print("i");
wait(400);
System.out.print("c");
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("t");
wait(400);
System.out.print("o");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("m");
wait(400);
System.out.print("e");
wait(400);
System.out.print("e");
wait(400);
System.out.print("t");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("y");
wait(400);
System.out.print("o");
wait(400);
System.out.print("u");
wait(400);
System.out.print(" ");
wait(400);
System.out.print(name);
wait(400);
System.out.println("!");
wait(400);
System.out.print("M");
wait(400); 
System.out.print("y");
wait(400);
System.out.print(" ");;
wait(400);
System.out.print("n");
wait(400);
System.out.print("a");
wait(400);
System.out.print("m");
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("i");
wait(400);
System.out.print("s");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("A");
wait(400);
System.out.print("n");
wait(400);
System.out.print("k");
wait(400);
System.out.print("u");
wait(400);
System.out.print("r");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("M");
wait(400);
System.out.print("a");
wait(400);
System.out.print("l");
wait(400);
System.out.print("l");
wait(400);
System.out.print("i");
wait(400);
System.out.print("c");
wait(400);
System.out.print("k");
wait(400);
System.out.print(".");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("I");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("l");
wait(400);
System.out.print("i");
wait(400);
System.out.print("v");
wait(400); 
System.out.print("e");
wait(400);
System.out.print(" ");;
wait(400);
System.out.print("i");
wait(400);
System.out.print("n");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("I");
wait(400);
System.out.print("n");
wait(400);
System.out.print("d");
wait(400);
System.out.print("i");
wait(400);
System.out.print("a");
wait(400);
System.out.println(".");
wait(400);
System.out.print("W");
wait(400);
System.out.print("h");
wait(400);
System.out.print("o");
wait(400);
System.out.print("m");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("d");
wait(400);
System.out.print("o");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("y");
wait(400);
System.out.print("o");
wait(400);
System.out.print("u");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("l");
wait(400);
System.out.print("o");
wait(400);
System.out.print("v");
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("t");
wait(400); 
System.out.print("h");
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("m");
wait(400);
System.out.print("o");
wait(400);
System.out.print("s");
wait(400);
System.out.print("t");
wait(400);
System.out.print("?");
a=sc.nextLine();
wait(400);
System.out.print("O");
wait(400);
System.out.print("o");
wait(400);
System.out.print(",");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("w");
wait(400);
System.out.print("h");
wait(400);
System.out.print("a");
wait(400);
System.out.print("t");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("a");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("s");
wait(400);
System.out.print("i");
wait(400);
System.out.print("m");
wait(400);
System.out.print("i");
wait(400);
System.out.print("l");
wait(400);
System.out.print("a");
wait(400);
System.out.print("r");
wait(400);
System.out.print("i");
wait(400);
System.out.print("t");
wait(400);
System.out.print("y");
wait(400);
System.out.print(",");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("I");
wait(400); 
System.out.print(" ");
wait(400);
System.out.print("a");;
wait(400);
System.out.print("l");
wait(400);
System.out.print("s");
wait(400);
System.out.print("o");
wait(400);
System.out.println(".");
wait(400);
System.out.print("O");
wait(400);
System.out.print("k");
wait(400);
System.out.print(",");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("s");
wait(400);
System.out.print("o");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("t");
wait(400);
System.out.print("o");
wait(400);
System.out.print("d");
wait(400);
System.out.print("a");
wait(400);
System.out.print("y");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("u");
wait(400);
System.out.print("p");
wait(400);
System.out.print("t");
wait(400);
System.out.print("o");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("t");
wait(400);
System.out.print("h");
wait(400);
System.out.print("i");
wait(400);
System.out.print("s");
wait(400);
System.out.print(".");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("B");
wait(400);
System.out.print("e");
wait(400); 
System.out.print(" ");
wait(400);
System.out.print("r");;
wait(400);
System.out.print("e");
wait(400);
System.out.print("a");
wait(400);
System.out.print("d");
wait(400);
System.out.print("y");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("f");
wait(400);
System.out.print("o");
wait(400);
System.out.print("r");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("t");
wait(400);
System.out.print("h");
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("n");
wait(400);
System.out.print("e");
wait(400);
System.out.print("x");
wait(400);
System.out.print("t");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("v");
wait(400);
System.out.print("e");
wait(400);
System.out.print("r");
wait(400);
System.out.print("s");
wait(400);
System.out.print("i");
wait(400);
System.out.print("o");
wait(400);
System.out.print("n");
wait(400);
System.out.println(".");
wait(400);
System.out.print("P");
wait(400);
System.out.print("l");
wait(400);
System.out.print("e");
wait(400); 
System.out.print("a");
wait(400);
System.out.print("z");;
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("g");
wait(400);
System.out.print("i");
wait(400);
System.out.print("v");
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("m");
wait(400);
System.out.print("e");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("a");
wait(400);
System.out.print(" ");
wait(400);
System.out.print("s");
wait(400);
System.out.print("t");
wait(400);
System.out.print("a");
wait(400);
System.out.print("r");
wait(400);
System.out.print("🌟");
wait(400);
System.out.print("🌟");
wait(400);
System.out.print("🌟");
}
}